version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  release:
    executor:
        name: node/default
        tag: '22.2.0'
    steps:
      - checkout
      - node/install-packages
      - run: npx eslint .
      - run: npx prettier --check .
      - run: npx semantic-release

workflows:
  test_and_release:
    jobs:
      - node/test:
          version: '22.2.0'
          pkg-manager: npm
      - release:
          requires:
            - node/test
